services:
  paypal-ipn-bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/paypal-ipn
    depends_on:
      - mongo
    restart: unless-stopped
  
  mongo:
    image: mongo:7
    volumes:
      - ./mongodata:/data/db
    restart: unless-stopped
